### ISSUE TITLE
Category rules match requirements error

### ISSUE THREAD

**Issue by ZeroMinded** [BunqCommunity/BunqDesktop#228]
## Bug report
When trying to add a new Category Rule

Clicking to change the "Match requirements" function results in the error below on
`Windows 10 & MacOSX 10.12 and BunqDesktop 0.8.9`.

Windows error log:
```
TypeError: Cannot read property 'focus' of null
    at t.value [as focus] (file:///C:/Users/<USERNAME>/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/BunqDesktop.js:1:385777)
    at Object.value [as onEnter] (file:///C:/Users/<USERNAME>/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/BunqDesktop.js:1:386048)
    at Object.value [as onEnter] (file:///C:/Users/<USERNAME>/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/BunqDesktop.js:1:1683437)
    at Object.value [as onEnter] (file:///C:/Users/<USERNAME>/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/BunqDesktop.js:1:1702511)
    at t.performEnter (file:///C:/Users/<USERNAME>/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/BunqDesktop.js:1:97711)
    at t.updateStatus (file:///C:/Users/<USERNAME>/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/BunqDesktop.js:1:97412)
    at t.componentDidMount (file:///C:/Users/<USERNAME>/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/BunqDesktop.js:1:96645)
    at commitLifeCycles (file:///C:/Users/<USERNAME>/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/BunqDesktop.js:1:1262364)
    at C (file:///C:/Users/<USERNAME>/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/BunqDesktop.js:1:1250172)
    at S (file:///C:/Users/<USERNAME>/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/BunqDesktop.js:1:1248982)```

**Comment by Crecket** [comment]
Fixed in the current Dev version 👍 will try to release the new version this week.

Thanks for the bug report
