### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by baum1234** [bunqCommunity/bunqDesktop#556]
I have the same bug with the Version 0.9.8 as described here #536 on my macos Catalina.

Apperently it should be fixed in 1.0.0. So I downloaded the nightly build and I get the following error:

`Uncaught Exception:
Error: Cannot find module 'electron-devtools-installer'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/Volumes/bunqDesktop 0.9.8/bunqDesktop.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Volumes/bunqDesktop 0.9.8/bunqDesktop.app/Contents/Resources/app.asar/app/background.js:14:24
    at Object.<anonymous> (/Volumes/bunqDesktop 0.9.8/bunqDesktop.app/Contents/Resources/app.asar/app/background.js:895:2)
    at Object.<anonymous> (/Volumes/bunqDesktop 0.9.8/bunqDesktop.app/Contents/Resources/app.asar/app/background.js:897:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)`

**Comment by firstred** [comment]
@baum1234 Thanks for letting us know!

Issue #536 has been solved. bunq changed the endpoints and all we needed to do was to update. 
We are currently working on updating the build as well, so your report is incredibly helpful!

I think it's caused by the fact that it is trying to install some developer extensions on the production version, which shouldn't happen. We'll have a look at it.

**Comment by baum1234** [comment]
Ah okay great @firstred 
When are you going to release the next version to homebrew?
