### ISSUE TITLE
"Something went wrong!"

### ISSUE THREAD

**Issue by CoreISP** [bunqCommunity/bunqDesktop#567]
Hi,

After having updated to 0.9.9, the app now constantly shows an error:

Something went wrong!
TypeError: Cannot read property 'image' of undefined
    at t.value (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/bunqDesktop.js:910:37396)
    at Qa (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3036:70885)
    at Ya (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3036:70680)
    at Os (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3036:106071)
    at Ou (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3036:90475)
    at Tu (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3036:90400)
    at vu (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3036:87727)
    at file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3036:45833
    at t.unstable_runWithPriority (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3056:3460)
    at qi (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3036:45543)

I'm logged in using oAuth.

**Comment by firstred** [comment]
Hi,

Thanks for posting the issue and sorry for the long wait. macOS builds have always been a black box for us, since we don't have the devices to test it properly and fully depend on the macOS build tools made by Electron. I have been trying to reproduce this on Linux and Windows but wasn't able to, so it seems to be an isolated issue on macOS only.
I am currently updating an old Mac as I am writing this, to see if I can run the application on macOS.

Just to make sure we've got all the info to reproduce it, you are using:
- macOS (Catalina?)
- bunqDesktop 0.99
- OAuth authentication

Did you limit the OAuth scope in any way? Remove permissions to do certain things? Thanks in advance!

**Comment by CoreISP** [comment]
@firstred Hi, sorry for the long wait from my part this time haha. Notifications here no longer work as expected I just found out.

Anyway, correct. MacOS Catalina, bunqDesktop, oAuth.
I don't believe I've limited anything, pretty sure there's not much control over oAuth - the only thing you have to do is select all the accounts you want to give bunqDesktop read-access to. (Which used to be *a lot* easier by the way, not sure why they changed it like this.) 

So the login goes fine, generates a QR-code to scan with bunq app. I accept in bunq app, bunqDesktop notices and then you have to confirm logging in (set key). That goes as expected. And then it dies with the above error and says "Return to Dashboard". 

If you need more details, please do let me know. I'll try to keep a better eye on this now, hehe.
