### ISSUE TITLE
Cannot read property 'amount_inquired' of null

### ISSUE THREAD

**Issue by sKiLdUsT** [bunqCommunity/bunqDesktop#585]
While setting up the app, after loading all card data and trying to display my account history, the following error appears and the app is unusable, except for the menu open button.

```
TypeError: Cannot read property 'amount_inquired' of null
    at t.value (AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/bunqDesktop.js:470:4298)
    at Qa (AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:70885)
    at Ya (AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:70680)
    at Os (AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:106071)
    at Ou (AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:90475)
    at Tu (AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:90400)
    at vu (AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:87727)
    at AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:45833
    at t.unstable_runWithPriority (AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3056:3460)
    at qi (AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:45543)
```

**Comment by SnowBlinderP** [comment]
Getting the Same Error with Existing Installations (PC and Laptop)

`TypeError: Cannot read property 'amount_inquired' of null
    at t.value (file:///C:/Users/paulo/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/bunqDesktop.js:470:4298)
    at Qa (file:///C:/Users/paulo/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:70885)
    at Ya (file:///C:/Users/paulo/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:70680)
    at Os (file:///C:/Users/paulo/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:106071)
    at Ou (file:///C:/Users/paulo/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:90475)
    at Tu (file:///C:/Users/paulo/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:90400)
    at vu (file:///C:/Users/paulo/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:87727)
    at file:///C:/Users/paulo/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:45833
    at t.unstable_runWithPriority (file:///C:/Users/paulo/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3056:3460)
    at qi (file:///C:/Users/paulo/AppData/Local/Programs/bunqdesktop/resources/app.asar/app/react/vendor.bundle.js:3036:45543)`

**Comment by SnowBlinderP** [comment]
Addition: 

After getting Notification for the Background Events and Clicking on Back then the Normal UI starts and works

**Comment by SnowBlinderP** [comment]
**push**
